version: '3.1'

services:
  rmq:
    image: rabbitmq:3-management
    container_name: rmq
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  online-compiler:
    image: online-compiler-img
    container_name: online-compiler
    environment:
      MQ_HOST: rmq
      REDIS_HOST: redis
      COMPILER_TMP_FOLDER : /opt/app/temp/
      HOST_TMP_FOLDER : /home/amit/tmp/
    ports:
      - "8090:8090"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/amit/tmp:/opt/app/temp"
    depends_on:
      - rmq
      - redis